extern const GeoLayout starstone_geo[];
extern Lights1 starstone_f3d_material_001_lights;
extern Lights1 starstone_f3d_material_lights;
extern u8 starstone_gradient_ci4[];
extern u8 starstone_gradient_ci4_pal_rgba16[];
extern u8 starstone_starstone_ci8[];
extern u8 starstone_starstone_ci8_pal_rgba16[];
extern Vtx starstone_Circle_mesh_layer_1_vtx_0[24];
extern Gfx starstone_Circle_mesh_layer_1_tri_0[];
extern Vtx starstone_Circle_mesh_layer_1_vtx_1[32];
extern Gfx starstone_Circle_mesh_layer_1_tri_1[];
extern Gfx mat_starstone_f3d_material_001[];
extern Gfx mat_revert_starstone_f3d_material_001[];
extern Gfx mat_starstone_f3d_material[];
extern Gfx mat_revert_starstone_f3d_material[];
extern Gfx starstone_Circle_mesh_layer_1[];
extern Gfx starstone_material_revert_render_settings[];
