#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "common0.h"

#include "blue_coin_switch/geo.inc.c"
// Hmm, this is included earlier.
#include "test_platform/geo.inc.c"
#include "amp/geo.inc.c"
#include "cannon_lid/geo.inc.c"
#include "cannon_base/geo.inc.c"
#include "cannon_barrel/geo.inc.c"
#include "chuckya/geo.inc.c"
#include "purple_switch/geo.inc.c"
#include "checkerboard_platform/geo.inc.c"
#include "heart/geo.inc.c"
#include "flyguy/geo.inc.c"
#include "breakable_box/geo.inc.c"
#include "bowling_ball/geo.inc.c"
#include "exclamation_box/geo.inc.c"
#include "goomba/geo.inc.c"
#include "bobomb/geo.inc.c"
#include "metal_box/geo.inc.c"
#include "exclamation_box_outline/geo.inc.c"
#include "koopa_shell/geo.inc.c"

#include "beat_push/geo.inc.c"
#include "bowstring/geo.inc.c"
#include "piano_key/geo.inc.c"
#include "starstone/geo.inc.c"
#include "drum/geo.inc.c"
#include "violoncello/geo.inc.c"
#include "violin/geo.inc.c"
#include "viola/geo.inc.c"
#include "contrabass/geo.inc.c"
#include "elec_guitar/geo.inc.c"
#include "piano/geo.inc.c"
#include "trumpet/geo.inc.c"
#include "trombone/geo.inc.c"
#include "alto_sax/geo.inc.c"
#include "tenor_sax/geo.inc.c"
#include "bass_guitar/geo.inc.c"
#include "songbi/geo.inc.c"
#include "luigi/geo.inc.c"
#include "broken_piano/geo.inc.c"