extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_sm64_material_layer1_area1_lights;
extern Lights1 bob_dl_f3d_material_layer1_area1_lights;
extern u8 bob_dl_RMGP01_0577f4dc_14_ci8[];
extern u8 bob_dl_RMGP01_0577f4dc_14_ci8_pal_rgba16[];
extern u8 bob_dl_bricks_ci8[];
extern u8 bob_dl_bricks_ci8_pal_rgba16[];
extern Vtx bob_dl_Cube_mesh_vtx_0[73];
extern Gfx bob_dl_Cube_mesh_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_sm64_material_layer1_area1[];
extern Gfx mat_revert_bob_dl_sm64_material_layer1_area1[];
extern Gfx mat_bob_dl_f3d_material_layer1_area1[];
extern Gfx mat_revert_bob_dl_f3d_material_layer1_area1[];
extern Gfx bob_dl_Cube_mesh[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
