extern const GeoLayout bowstring_geo[];
extern Lights1 bowstring_f3d_material_003_lights;
extern Lights1 bowstring_f3d_material_002_lights;
extern u8 bowstring_RMGP01_a81a1a44_14_ci8[];
extern u8 bowstring_RMGP01_a81a1a44_14_ci8_pal_rgba16[];
extern Vtx bowstring_bowstring_mesh_layer_1_vtx_0[22];
extern Gfx bowstring_bowstring_mesh_layer_1_tri_0[];
extern Vtx bowstring_bowstring_mesh_layer_1_vtx_1[84];
extern Gfx bowstring_bowstring_mesh_layer_1_tri_1[];
extern Gfx mat_bowstring_f3d_material_003[];
extern Gfx mat_bowstring_f3d_material_002[];
extern Gfx mat_revert_bowstring_f3d_material_002[];
extern Gfx bowstring_bowstring_mesh_layer_1[];
extern Gfx bowstring_material_revert_render_settings[];
